namespace Edelstein.Data.Msts;

public enum MissionType
{
    None = 0,
    Main = 1,
    Daily = 2,
    Weekly = 3,
    Event = 4,
    EventDaily = 5,
    Bingo = 6,
    Chat = 7,
    Subscription = 8,
    EventIconCollection = 9,
    EventIconCollectionDaily = 10,
    EventMulti = 11,
    EventMultiDaily = 12,
    EventSoloPoint = 13,
    EventSoloPointDaily = 14,
    CampaignDaily1 = 15,
    Campaign1 = 16,
    CampaignDaily2 = 17,
    Campaign2 = 18,
    CampaignDaily3 = 19,
    Campaign3 = 20,
    UserBirthdayChat = 21,
    EventStar = 22,
    EventStarDaily = 23,
    CampaignDaily4 = 24,
    Campaign4 = 25,
    CampaignDaily5 = 26,
    Campaign5 = 27,
    CampaignDaily6 = 28,
    Campaign6 = 29,
    CampaignDaily7 = 30,
    Campaign7 = 31,
    CampaignDaily8 = 32,
    Campaign8 = 33,
    CampaignDaily9 = 34,
    Campaign9 = 35
}
